Error	23:07:12 [TypeOrmModule] Unable to connect to the database. Retrying (1)... - {
  stack: [
    'AggregateError: \n' +
      '    at internalConnectMultiple (node:net:1116:18)\n' +
      '    at afterConnectMultiple (node:net:1683:7)\n' +
      '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
  ]
}
Error	23:07:15 [TypeOrmModule] Unable to connect to the database. Retrying (2)... - {
  stack: [
    'Error: DataSource with name "default" has already added.\n' +
      '    at addTransactionalDataSource (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm-transactional@0.5.0_reflect-metadata@0.2.2_typeorm@0.3.20/node_modules/typeorm-transactional/src/common/index.ts:211:11)\n' +
      '    at dataSourceFactory (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/app.module.ts:24:42)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/@nestjs+typeorm@10.0.2_@nestjs+common@10.3.9_@nestjs+core@10.3.9_reflect-metadata@0.2.2_rxjs@7.8.1_typeorm@0.3.20/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:169:36\n' +
      '    at Observable._subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n' +
      '    at Observable._trySubscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18\n' +
      '    at Object.errorContext (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n' +
      '    at Observable.subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:220:5)\n' +
      '    at subscribeForRetryWhen (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:74:25)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:85:28'
  ]
}
Error	23:07:18 [TypeOrmModule] Unable to connect to the database. Retrying (3)... - {
  stack: [
    'Error: DataSource with name "default" has already added.\n' +
      '    at addTransactionalDataSource (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm-transactional@0.5.0_reflect-metadata@0.2.2_typeorm@0.3.20/node_modules/typeorm-transactional/src/common/index.ts:211:11)\n' +
      '    at dataSourceFactory (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/app.module.ts:24:42)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/@nestjs+typeorm@10.0.2_@nestjs+common@10.3.9_@nestjs+core@10.3.9_reflect-metadata@0.2.2_rxjs@7.8.1_typeorm@0.3.20/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:169:36\n' +
      '    at Observable._subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n' +
      '    at Observable._trySubscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18\n' +
      '    at Object.errorContext (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n' +
      '    at Observable.subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:220:5)\n' +
      '    at subscribeForRetryWhen (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:74:25)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:85:28'
  ]
}
Error	23:07:21 [TypeOrmModule] Unable to connect to the database. Retrying (4)... - {
  stack: [
    'Error: DataSource with name "default" has already added.\n' +
      '    at addTransactionalDataSource (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm-transactional@0.5.0_reflect-metadata@0.2.2_typeorm@0.3.20/node_modules/typeorm-transactional/src/common/index.ts:211:11)\n' +
      '    at dataSourceFactory (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/app.module.ts:24:42)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/@nestjs+typeorm@10.0.2_@nestjs+common@10.3.9_@nestjs+core@10.3.9_reflect-metadata@0.2.2_rxjs@7.8.1_typeorm@0.3.20/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:169:36\n' +
      '    at Observable._subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n' +
      '    at Observable._trySubscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18\n' +
      '    at Object.errorContext (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n' +
      '    at Observable.subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:220:5)\n' +
      '    at subscribeForRetryWhen (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:74:25)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:85:28'
  ]
}
Error	23:07:24 [TypeOrmModule] Unable to connect to the database. Retrying (5)... - {
  stack: [
    'Error: DataSource with name "default" has already added.\n' +
      '    at addTransactionalDataSource (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm-transactional@0.5.0_reflect-metadata@0.2.2_typeorm@0.3.20/node_modules/typeorm-transactional/src/common/index.ts:211:11)\n' +
      '    at dataSourceFactory (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/app.module.ts:24:42)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/@nestjs+typeorm@10.0.2_@nestjs+common@10.3.9_@nestjs+core@10.3.9_reflect-metadata@0.2.2_rxjs@7.8.1_typeorm@0.3.20/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:169:36\n' +
      '    at Observable._subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n' +
      '    at Observable._trySubscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18\n' +
      '    at Object.errorContext (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n' +
      '    at Observable.subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:220:5)\n' +
      '    at subscribeForRetryWhen (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:74:25)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:85:28'
  ]
}
Error	23:07:27 [TypeOrmModule] Unable to connect to the database. Retrying (6)... - {
  stack: [
    'Error: DataSource with name "default" has already added.\n' +
      '    at addTransactionalDataSource (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm-transactional@0.5.0_reflect-metadata@0.2.2_typeorm@0.3.20/node_modules/typeorm-transactional/src/common/index.ts:211:11)\n' +
      '    at dataSourceFactory (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/app.module.ts:24:42)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/@nestjs+typeorm@10.0.2_@nestjs+common@10.3.9_@nestjs+core@10.3.9_reflect-metadata@0.2.2_rxjs@7.8.1_typeorm@0.3.20/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:169:36\n' +
      '    at Observable._subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n' +
      '    at Observable._trySubscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18\n' +
      '    at Object.errorContext (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n' +
      '    at Observable.subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:220:5)\n' +
      '    at subscribeForRetryWhen (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:74:25)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:85:28'
  ]
}
Error	23:07:30 [TypeOrmModule] Unable to connect to the database. Retrying (7)... - {
  stack: [
    'Error: DataSource with name "default" has already added.\n' +
      '    at addTransactionalDataSource (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm-transactional@0.5.0_reflect-metadata@0.2.2_typeorm@0.3.20/node_modules/typeorm-transactional/src/common/index.ts:211:11)\n' +
      '    at dataSourceFactory (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/app.module.ts:24:42)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/@nestjs+typeorm@10.0.2_@nestjs+common@10.3.9_@nestjs+core@10.3.9_reflect-metadata@0.2.2_rxjs@7.8.1_typeorm@0.3.20/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:169:36\n' +
      '    at Observable._subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n' +
      '    at Observable._trySubscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18\n' +
      '    at Object.errorContext (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n' +
      '    at Observable.subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:220:5)\n' +
      '    at subscribeForRetryWhen (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:74:25)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:85:28'
  ]
}
Error	23:07:33 [TypeOrmModule] Unable to connect to the database. Retrying (8)... - {
  stack: [
    'Error: DataSource with name "default" has already added.\n' +
      '    at addTransactionalDataSource (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm-transactional@0.5.0_reflect-metadata@0.2.2_typeorm@0.3.20/node_modules/typeorm-transactional/src/common/index.ts:211:11)\n' +
      '    at dataSourceFactory (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/app.module.ts:24:42)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/@nestjs+typeorm@10.0.2_@nestjs+common@10.3.9_@nestjs+core@10.3.9_reflect-metadata@0.2.2_rxjs@7.8.1_typeorm@0.3.20/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:169:36\n' +
      '    at Observable._subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n' +
      '    at Observable._trySubscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18\n' +
      '    at Object.errorContext (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n' +
      '    at Observable.subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:220:5)\n' +
      '    at subscribeForRetryWhen (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:74:25)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:85:28'
  ]
}
Error	23:07:40 [TypeOrmModule] Unable to connect to the database. Retrying (1)... - {
  stack: [
    "Error: Unknown database 'vapeshop'\n" +
      '    at Packet.asError (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/packets/packet.js:728:17)\n' +
      '    at ClientHandshake.execute (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/commands/command.js:29:26)\n' +
      '    at PoolConnection.handlePacket (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:481:34)\n' +
      '    at PacketParser.onPacket (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:97:12)\n' +
      '    at PacketParser.executeStart (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/packet_parser.js:75:16)\n' +
      '    at Socket.<anonymous> (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:104:25)\n' +
      '    at Socket.emit (node:events:519:28)\n' +
      '    at addChunk (node:internal/streams/readable:559:12)\n' +
      '    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n' +
      '    at Socket.Readable.push (node:internal/streams/readable:390:5)'
  ]
}
Error	23:07:43 [TypeOrmModule] Unable to connect to the database. Retrying (2)... - {
  stack: [
    'Error: DataSource with name "default" has already added.\n' +
      '    at addTransactionalDataSource (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm-transactional@0.5.0_reflect-metadata@0.2.2_typeorm@0.3.20/node_modules/typeorm-transactional/src/common/index.ts:211:11)\n' +
      '    at dataSourceFactory (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/app.module.ts:24:42)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/@nestjs+typeorm@10.0.2_@nestjs+common@10.3.9_@nestjs+core@10.3.9_reflect-metadata@0.2.2_rxjs@7.8.1_typeorm@0.3.20/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:169:36\n' +
      '    at Observable._subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n' +
      '    at Observable._trySubscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18\n' +
      '    at Object.errorContext (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n' +
      '    at Observable.subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:220:5)\n' +
      '    at subscribeForRetryWhen (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:74:25)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:85:28'
  ]
}
Error	23:07:46 [TypeOrmModule] Unable to connect to the database. Retrying (3)... - {
  stack: [
    'Error: DataSource with name "default" has already added.\n' +
      '    at addTransactionalDataSource (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm-transactional@0.5.0_reflect-metadata@0.2.2_typeorm@0.3.20/node_modules/typeorm-transactional/src/common/index.ts:211:11)\n' +
      '    at dataSourceFactory (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/app.module.ts:24:42)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/@nestjs+typeorm@10.0.2_@nestjs+common@10.3.9_@nestjs+core@10.3.9_reflect-metadata@0.2.2_rxjs@7.8.1_typeorm@0.3.20/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:169:36\n' +
      '    at Observable._subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n' +
      '    at Observable._trySubscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:244:19)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:234:18\n' +
      '    at Object.errorContext (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n' +
      '    at Observable.subscribe (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Observable.ts:220:5)\n' +
      '    at subscribeForRetryWhen (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:74:25)\n' +
      '    at /Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/retryWhen.ts:85:28'
  ]
}
Error	23:10:44 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:44 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:44 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:44 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:45 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:45 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:45 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:45 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:46 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:46 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:47 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:47 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:48 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:49 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:49 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:50 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:10:51 Redis error connect ECONNREFUSED 127.0.0.1:6379 - {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379,
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:6379\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)\n' +
    '    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)'
}
Error	23:14:26 [UsersService] Table 'vapeshop.users' doesn't exist - {
  stack: [
    "QueryFailedError: Table 'vapeshop.users' doesn't exist\n" +
      '    at Query.onResult (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_mysql2@3.10.1_ts-node@10.9.2/src/driver/mysql/MysqlQueryRunner.ts:246:33)\n' +
      '    at Query.execute (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/commands/command.js:36:14)\n' +
      '    at PoolConnection.handlePacket (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:481:34)\n' +
      '    at PacketParser.onPacket (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:97:12)\n' +
      '    at PacketParser.executeStart (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/packet_parser.js:75:16)\n' +
      '    at Socket.<anonymous> (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:104:25)\n' +
      '    at Socket.emit (node:events:519:28)\n' +
      '    at addChunk (node:internal/streams/readable:559:12)\n' +
      '    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n' +
      '    at Socket.Readable.push (node:internal/streams/readable:390:5)'
  ],
  error: {
    query: 'INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (?, ?, DEFAULT, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)',
    parameters: [ 6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', 'notemean', 1 ],
    driverError: {
      code: 'ER_NO_SUCH_TABLE',
      errno: 1146,
      sqlState: '42S02',
      sqlMessage: "Table 'vapeshop.users' doesn't exist",
      sql: "INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', DEFAULT, 'notemean', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)"
    },
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'vapeshop.users' doesn't exist",
    sql: "INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', DEFAULT, 'notemean', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)"
  },
  query: 'INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (?, ?, DEFAULT, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)',
  parameters: [ 6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', 'notemean', 1 ],
  driverError: {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'vapeshop.users' doesn't exist",
    sql: "INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', DEFAULT, 'notemean', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)"
  },
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: "Table 'vapeshop.users' doesn't exist",
  sql: "INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', DEFAULT, 'notemean', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)"
}
Error	23:17:19 [UsersService] Unknown column 'firsName' in 'field list' - {
  stack: [
    "QueryFailedError: Unknown column 'firsName' in 'field list'\n" +
      '    at Query.onResult (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/typeorm@0.3.20_ioredis@5.4.1_mysql2@3.10.1_ts-node@10.9.2/src/driver/mysql/MysqlQueryRunner.ts:246:33)\n' +
      '    at Query.execute (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/commands/command.js:36:14)\n' +
      '    at PoolConnection.handlePacket (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:481:34)\n' +
      '    at PacketParser.onPacket (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:97:12)\n' +
      '    at PacketParser.executeStart (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/packet_parser.js:75:16)\n' +
      '    at Socket.<anonymous> (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:104:25)\n' +
      '    at Socket.emit (node:events:519:28)\n' +
      '    at addChunk (node:internal/streams/readable:559:12)\n' +
      '    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n' +
      '    at Socket.Readable.push (node:internal/streams/readable:390:5)'
  ],
  error: {
    query: 'INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (?, ?, DEFAULT, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)',
    parameters: [ 6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', 'notemean', 1 ],
    driverError: {
      code: 'ER_BAD_FIELD_ERROR',
      errno: 1054,
      sqlState: '42S22',
      sqlMessage: "Unknown column 'firsName' in 'field list'",
      sql: "INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', DEFAULT, 'notemean', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)"
    },
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'firsName' in 'field list'",
    sql: "INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', DEFAULT, 'notemean', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)"
  },
  query: 'INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (?, ?, DEFAULT, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)',
  parameters: [ 6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', 'notemean', 1 ],
  driverError: {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'firsName' in 'field list'",
    sql: "INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', DEFAULT, 'notemean', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)"
  },
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'firsName' in 'field list'",
  sql: "INSERT INTO `users`(`id`, `firstName`, `avatar`, `username`, `isActive`, `isAdmin`, `isBanned`, `balance`, `discount`, `updated`, `created`) VALUES (6046211519, '𝙉𝙊𝙏𝙀𝙈𝙀𝘼𝙉', DEFAULT, 'notemean', 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT) ON DUPLICATE KEY UPDATE `isActive` = VALUES(`isActive`), `username` = VALUES(`username`), `firsName` = VALUES(`firsName`), `avatar` = VALUES(`avatar`)"
}
Error	23:26:30 [ExceptionsHandler] 400: Bad Request: inline keyboard button Web App URL 'http://127.0.0.1:3001' is invalid: Only HTTPS links are allowed - {
  stack: [
    "Error: 400: Bad Request: inline keyboard button Web App URL 'http://127.0.0.1:3001' is invalid: Only HTTPS links are allowed\n" +
      '    at Telegram.callApi (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/telegraf@4.16.3/node_modules/telegraf/lib/core/network/client.js:315:19)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at BotUpdate.onStart (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/bot/bot.update.ts:9:5)'
  ]
}
Error	23:34:26 [ExceptionsHandler] 400: Bad Request: inline keyboard button Web App URL 'http://127.0.0.1:3001' is invalid: Only HTTPS links are allowed - {
  stack: [
    "Error: 400: Bad Request: inline keyboard button Web App URL 'http://127.0.0.1:3001' is invalid: Only HTTPS links are allowed\n" +
      '    at Telegram.callApi (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/telegraf@4.16.3/node_modules/telegraf/lib/core/network/client.js:315:19)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at BotUpdate.onStart (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/bot/bot.update.ts:9:5)'
  ]
}
Error	23:40:11 [ExceptionsHandler] 400: Bad Request: inline keyboard button Web App URL 'https://localhost:3000' is invalid: Wrong HTTP URL - {
  stack: [
    "Error: 400: Bad Request: inline keyboard button Web App URL 'https://localhost:3000' is invalid: Wrong HTTP URL\n" +
      '    at Telegram.callApi (/Users/admin/WebstormProjects/vapeshop-webapp/node_modules/.pnpm/telegraf@4.16.3/node_modules/telegraf/lib/core/network/client.js:315:19)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at BotUpdate.onStart (/Users/admin/WebstormProjects/vapeshop-webapp/apps/server/src/bot/bot.update.ts:9:5)'
  ]
}
